apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicename
  namespace: namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicename
  template:
    metadata:
      labels:
        app: servicename
    spec:
      containers:
      - name: servicename
        image: image registry
        imagePullSecrets:
          - name: image secrets
        imagePullPolicy: Always
        ports:
        - containerPort: 80